### ISSUE TITLE
`Node.remove_child`: `.item` bug (also affects `Node.remove_children`)

### ISSUE THREAD

**Issue by ricardo-reis-1970** [Luke-Poeppel/treeplotter#37]
# Motivation
I'm using [`PyCG`](https://github.com/vitsalis/PyCG) to gather a call graph from my codebase. I came to `treeplot` because I needed something to visualize the generated JSON graph. Since the visualization question is often asked regarding `PyCG`, I'm trying to come up with a solution based on this module.

This will involve a few JSON tweaks, but also a small add to `treeplot`. I'm opening another issue regarding those. Please refer to issue #38.

Note to self: I need to start doing pull requests...

# `remove_child()`
In the `Node.remove_child()` method, the node is checked for its presence in the children. This is done by value, in the following way (tree.py, line 107):
```python
if child_node.item.value not in self.children:
```
This raises an `AttributeError: 'Node' object has no attribute 'item'`. In order to fix this, I tried refactoring the method into this:
```python
	def remove_child(self, child_node):
		if child_node not in self.children:
			raise NodeException("This parent does not have that child.")
		self.children.remove(child_node)
		return
```
# `remove_children()`
Now, the issue is that it _works_, meaning that now there's another error: `RuntimeError: Set changed size during iteration`. This is due to the fact that in the `Node.remove_children()` method, line 113 reads:
```python
		for this_child in children_nodes:
```

This could never have worked, indeed, because it's cycling over a set that is being changed, especially if we do something as natural and innocent as:
```python
some_node.remove_children(some_node.children)
```

Again — and partly due to a lack of docstrings —, one walks easily into these. The solution I propose is:
```python
		for this_child in tuple(children_nodes):
```
I'm using `tuple` because I'm not going to change it and, therefore, I don't need the heavier and slower `list`, that seems to be the universal go-to-item in these cases. This way, I'm forcing an abstraction from the original set (a copy), that will guarantee the maintenance of the cycle throughout the deletion.

# Wrap up
The new version I got looks like this (tree.py, lines 106-118):
```python
	def remove_child(self, child_node):
		if child_node not in self.children:
			raise NodeException("This parent does not have that child.")
		self.children.remove(child_node)
		return

	def remove_children(self, children_nodes):
		for this_child in tuple(children_nodes):
			try:
				self.remove_child(this_child)
			except KeyError:
				raise NodeException("One of the values in children_nodes was not found.")
		return

```
With these, here's a small session I can run without any exceptions:
```python
>>> from treeplotter.tree import Node, Tree
>>> root=Node(value=0, name='main')
>>> root.children = {Node(name=f'{i}', value=i) for i in range(1,5)}
>>> tree = Tree(root=root)
>>> root.children
{<tree.Node name=1>, <tree.Node name=3>, <tree.Node name=2>, <tree.Node name=4>}
>>> root.remove_children(root.children)
>>> root.children
set()
>>>
```

**Comment by Luke-Poeppel** [comment]
Hi @ricardo-reis-1970! Thanks so much for the detailed info here and in #38. I'm thrilled to hear that the package is useful for your work. (`treeplotter` still requires lots of smoothing, so testing and bug reports are much appreciated.) My schedule is quite packed for the next two or three days, but I'll give a detailed reply to both issues sometime in the first half of the coming week. Quickly reading through, everything you wrote seems quite reasonable. Feel free to keep the issues as-is or file a Pull Request (either option works for me). 

Thanks again for filing! 👍
