### ISSUE TITLE
Finding nodes by name

### ISSUE THREAD

**Issue by ricardo-reis-1970** [Luke-Poeppel/treeplotter#38]
# Motivation
Further to issue #37, my JSON graph is flattened and I need to build it up. For this, I have the constant need to decide whether to add a certain node (if it doesn't exist), or to increment its count (in case I find it). For this, I'll need a method to find a node by name.

I believe that such a method should exist. Fully aware that names might not be unique — although my process will guarantee these! —, I would argue that values are also potentially non-unique, and yet we have a method to find these (tree.py, lines 128-133):
```python
	def get_child_by_value(self, value):
		for this_child in self.children:
			if this_child.value == value:
				return this_child
		else:
			return None
```

# `get_child_by_name`
My proposal is the following:
```python
	def get_child_by_name(self, name):
		for this_child in self.children:
			if this_child.name == name:
				return this_child
		else:
			return None
```

Naturally, the next step would be a `Node` method that could find one such node recursively, from a certain node downwards. It could be this same method, with a tweak:
```python
	def get_child_by_name(self, name, recurse=False):
		for this_child in self.children:
			if this_child.name == name:
				return this_child
			elif recurse:
				res = this_child.get_child_by_name(self, name, recurse)
				if res:
					return res
		else:
			return None
```
This is a depth-first implementation, defaulting to non-recursive. For a breadth-first, we could putt the `elif` block into `for`'s `else` branch and inside another cycle: `for this_grandchild in this_child.children:`. Having both could look like the following:
```python
	def get_child_by_name(self, name):
		for this_child in self.children:
			if this_child.name == name:
				return this_child
		else:
			return None

	def get_child_by_name_depth(self, name):
		for this_child in self.children:
			if this_child.name == name:
				return this_child
			else:
				res = this_child.get_child_by_name_depth(name)
				if res:
					return res
		else:
			return None

	def get_child_by_name_breadth(self, name):
		for this_child in self.children:
			if this_child.name == name:
				return this_child
		else:
			for this_child in self.children:
				res = this_child.get_child_by_name_breadth(name)
				if res:
					return res
			else:
				return None
```

Let me know if this makes sense. I could just be inheriting the class `Node` and add these, but it really seems to me that this could benefit others.

**Comment by Luke-Poeppel** [comment]
Hi @ricardo-reis-1970. Thanks again for your detailed info (and apologies for my later-than-expected reply). I've just released a new version of `treeplotter`, v0.5.0, with the methods you've written above, along with your bugfix in #37. You've been fully credited in the CHANGELOG (and in the source). 

If you use pip, you should be able to upgrade with `pip3 install --upgrade treeplotter`. Otherwise, you can just `git pull` from master. If you have any problems –– or discover new issues with the package –– feel free to file additional issues!
